FSA-547 add limited hooks
humanmade/msm-sitemap pull request #6
Opened 2018-11-05 05:06 UTC by webecks

[FSA-547](https://humanmade.atlassian.net/browse/FSA-547) - Separate videos from current sitemap into its own sitemap

**There are 2 sitemaps generated from this code adjustment:**
- sitemap.xml
- sitemap-videos.xml

*I have:*
- [x] Written doc blocks and inline documentation on all new changes
- [x] Added the Jira reference as a prefix to the title of the PR
- [ ] Notes on how-to-test supplied in issue description on Jira
- [ ] WP CLI commands supplied in issue description on Jira
- [ ] As a developer, I've tested this on www-development.foxsportsasia.com

2018-11-08 23:14 UTC, tareiking commented
@webecks - was this meant to be opened against the `fs-master` branch? If so, can you edit the PR and change the base?

2018-11-09 04:31 UTC, webecks commented
@tareiking I changed the base.
There were 2 conflicts between fs-master and branch FSA-547-split-sitemap-by-posttype.
I fixed and merged it. But just realized that it might need to be merged by someone else (perhaps you) after the code changes are approved.
Could you please check? Thanks.

2018-11-11 20:43 UTC, tareiking requested changes
@webecks - you'll need to add the docblock. Otherwise, looks okay for usage on Fox ATM.

2018-11-11 20:43 UTC, tareiking commented on msm-sitemap.php
> +		do_action( 'msm_sitemap_rewrite_rule' );
Need a docblock to explain this action here.

2018-11-12 09:05 UTC, webecks reviewed
@tareiking is the current docblock okay?

2018-12-06 21:35 UTC, tareiking requested changes
@webecks tested locally, this creates the sitemaps as expected. Added a few comments.. getting close!

2018-12-06 21:35 UTC, tareiking commented on msm-sitemap.php
> +		$post_type = get_query_var( 'post_type' );
We should check if this post type is registered as well here using `post_type_exists`.

2018-12-06 21:35 UTC, tareiking commented on msm-sitemap.php
> +		 * @param type  $var Description.
This `param` isn't actually valid here.

2018-12-11 07:11 UTC, webecks commented
@tareiking I have updated the file.

2018-12-13 02:30 UTC, tareiking approved these changes
Approving recent changes, thanks @webecks

2018-12-13 02:30 UTC, merged